name: hello-world
'on': push
jobs:
  builds:
    runs-on: windows-latest
    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1
    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: 'https://org847ad10d.crm.dynamics.com/'
        user-name: 'bk@65bwhm.onmicrosoft.com'
        password-secret: '${{ secrets.MYREPO }}'
        solution-name: POCSolution
        solution-output-file: POCSolution.zip
        working-directory: out
   
